In [1]:
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
iris=datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
X = pd.DataFrame(iris.data)
y = pd.DataFrame(iris.target)
print(X.head())

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2


In [4]:
# Fitting Multiclass Logistic Classification to the Training set
regressor = LogisticRegression()

In [5]:
#Define 1-vs-Rest Strategy / Classifier
ovr = OneVsRestClassifier(regressor)

#fit model to training data
ovr.fit(X_train, y_train)

#Predications
ovr_pred = ovr.predict(X_test)

#Adding Predictions to Test Dataset
ovr_df = X_test.copy()
ovr_df.insert(4,"Actual",y_test, True)
ovr_df.insert(5,"Predicted",ovr_pred, True)
ovr_df.head()

0    1    2    3  Actual  Predicted
0  6.1  2.8  4.7  1.2       1          1
1  5.7  3.8  1.7  0.3       0          0
2  7.7  2.6  6.9  2.3       2          2
3  6.0  2.9  4.5  1.5       1          1
4  6.8  2.8  4.8  1.4       1          1

In [6]:
# Confusion Matrix
cm = confusion_matrix(y_test, ovr_pred)
print(cm)

[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]


In [7]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('Accuracy of the multiclass logistic classification is: ', corrPred/(cm.sum()))

Correct predictions:  29
False predictions 1
Accuracy of the multiclass logistic classification is:  0.9666666666666667
